import { NgModule } from "@angular/core";
import { HTTP_INTERCEPTORS } from "@angular/common/http";
import { AbpHttpInterceptor } from "abp-ng2-module";

import * as ApiServiceProxies from "./service-proxies";

@NgModule({
  providers: [
    ApiServiceProxies.AccountTypeServiceProxy,
    ApiServiceProxies.MainHeadServiceProxy,
    ApiServiceProxies.ChartOfAccountsServiceProxy,
    ApiServiceProxies.RoleServiceProxy,
    ApiServiceProxies.SessionServiceProxy,
    ApiServiceProxies.TenantServiceProxy,
    ApiServiceProxies.UserServiceProxy,
    ApiServiceProxies.TokenAuthServiceProxy,
    ApiServiceProxies.AccountServiceProxy,
    ApiServiceProxies.ConfigurationServiceProxy,
    ApiServiceProxies.ContactPersonTypeServiceProxy,
    ApiServiceProxies.LanguageServiceProxy,
    ApiServiceProxies.EthnicitiesServiceProxy,
    ApiServiceProxies.SalesPersonTypeServiceProxy,
    ApiServiceProxies.SourceReferralTypeServiceProxy,
    ApiServiceProxies.GeneralEntityTypeServiceProxy,
    ApiServiceProxies.JobTitleServiceProxy,
    ApiServiceProxies.SpouseServiceProxy,
    ApiServiceProxies.ProductCategoryServiceProxy,
    ApiServiceProxies.CustomerServiceProxy,
    ApiServiceProxies.CompanyServiceProxy,
    ApiServiceProxies.VenderTypeServiceProxy,
    ApiServiceProxies.VenderServiceProxy,
    ApiServiceProxies.VendorContactInfoServiceProxy,
    ApiServiceProxies.ProductServiceServiceProxy,
    ApiServiceProxies.BankServiceProxy,
    ApiServiceProxies.CustomerTypesServiceProxy,
    ApiServiceProxies.InvoiceServiceProxy,
    ApiServiceProxies.PaymentMethodServiceProxy,
    ApiServiceProxies.EstimateServiceProxy,
    ApiServiceProxies.DLStatesServiceProxy,
    ApiServiceProxies.ReceivedPaymentServiceServiceProxy,
    ApiServiceProxies.SalesReceiptServiceProxy,
    ApiServiceProxies.MerchantServiceProxy,
    ApiServiceProxies.AttachmentServiceProxy,
    ApiServiceProxies.RecurringInvoiceServiceProxy,
    ApiServiceProxies.CustomerDiaryServiceProxy,
    ApiServiceProxies.TenureServiceProxy,
    ApiServiceProxies.LegalStatusServiceProxy,
    ApiServiceProxies.SalesTaxServiceProxy,
    ApiServiceProxies.TaxServiceMasterServiceProxy,
    ApiServiceProxies.PersonalTaxServiceProxy,
    ApiServiceProxies.PurchaseReceiptServiceServiceProxy,
    ApiServiceProxies.PurchaseInvoiceServiceServiceProxy,
    ApiServiceProxies.CorporateTaxServiceProxy,
    ApiServiceProxies.CreditNoteServiceServiceProxy,
    ApiServiceProxies.CalenderServiceServiceProxy,
    ApiServiceProxies.PersonalInformationServiceProxy,
    ApiServiceProxies.ContactDetailsServiceProxy,
    ApiServiceProxies.CheckServiceProxy,
    ApiServiceProxies.JournalVoucherServiceServiceProxy,
    ApiServiceProxies.CompanyDetailsServiceProxy,
    ApiServiceProxies.UserGroupsServiceProxy,
    ApiServiceProxies.TenantRegistationServiceProxy,
    ApiServiceProxies.EmployeActivitiesServiceProxy,
    ApiServiceProxies.DailyReceiptServiceProxy,
    ApiServiceProxies.GeneralLedgerServiceProxy,
    ApiServiceProxies.SourceReferalServiceProxy,
    ApiServiceProxies.CustomerLedgerServiceProxy,
    ApiServiceProxies.TrialBalanceServiceProxy,

    { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true },
  ],
})
export class ServiceProxyModule { }
